#!/bin/bash
# observe.sh — Run an observation pass over recent conversation history
# Usage: echo "conversation text" | ./observe.sh
#   or:  ./observe.sh < conversation.txt
#   or:  ./observe.sh --file /path/to/conversation.txt
#
# Output: Writes observation to memory/observations/YYYY-MM-DD-HH-MM.md
#         Updates memory/observer-state.json

set -e

export PATH="$HOME/.local/bin:$PATH"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=_log.sh
source "$SCRIPT_DIR/_log.sh" 2>/dev/null || true

MEMORY_DIR="${MEMORY_DIR:-$(dirname "$SCRIPT_DIR")}"
WORKSPACE_DIR="${WORKSPACE_DIR:-$(dirname "$MEMORY_DIR")}"
OBS_DIR="$MEMORY_DIR/observations"
STATE_FILE="$MEMORY_DIR/observer-state.json"
PROMPT_FILE="$MEMORY_DIR/OBSERVATION-PROMPT.md"

log info "enter" "{\"memoryDir\":\"$MEMORY_DIR\",\"autoReflect\":\"${AUTO_REFLECT:-0}\"}"

# Ensure directories exist
mkdir -p "$OBS_DIR"

# Bootstrap state file — jq's "read-update-rename" pattern below cannot
# create the file from nothing. Without this the first observation leaves
# a 0-byte .tmp and unprocessedObservationCount stays stuck at 1 forever,
# so AUTO_REFLECT thresholds never cross.
if [ ! -f "$STATE_FILE" ]; then
  echo '{}' > "$STATE_FILE"
  log info "bootstrap-state" "{\"path\":\"$STATE_FILE\"}"
fi

# Get conversation input
if [ "$1" = "--file" ] && [ -n "$2" ]; then
    CONVERSATION=$(cat "$2")
elif [ ! -t 0 ]; then
    CONVERSATION=$(cat)
else
    echo "Usage: echo 'conversation' | ./observe.sh"
    echo "   or: ./observe.sh --file /path/to/conversation.txt"
    exit 1
fi

if [ -z "$CONVERSATION" ]; then
    echo "Error: No conversation input provided"
    exit 1
fi

# Extract system prompt from OBSERVATION-PROMPT.md
# The system prompt is between the first pair of triple backticks in the "## System Prompt" section
SYSTEM_PROMPT=$(sed -n '/^## System Prompt/,/^## User Prompt/{ /^```$/,/^```$/{ /^```$/d; p; } }' "$PROMPT_FILE" | head -n -0)

# If extraction failed, use a simpler approach
if [ -z "$SYSTEM_PROMPT" ]; then
    echo "Warning: Could not extract system prompt from OBSERVATION-PROMPT.md, using embedded fallback"
    SYSTEM_PROMPT="You are the agent's memory consciousness. Extract structured observations from this conversation using XML tags: <observations>, <current-task>, <suggested-response>. Use priority emojis: 🔴 High, 🟡 Medium, 🟢 Low, ✅ Completed."
fi

# Substitute persona placeholders. AGENT_NAME defaults to "the agent",
# USER_NAME defaults to "the user" — keeps the prompt sensible if env
# vars are unset (e.g. fresh OSS install before `the-brain agent init`).
AGENT_NAME_RESOLVED="${AGENT_NAME:-the agent}"
USER_NAME_RESOLVED="${USER_NAME:-the user}"
SYSTEM_PROMPT=${SYSTEM_PROMPT//\{AGENT_NAME\}/$AGENT_NAME_RESOLVED}
SYSTEM_PROMPT=${SYSTEM_PROMPT//\{USER_NAME\}/$USER_NAME_RESOLVED}

# Generate timestamp for filename.
# Second resolution (not minute) so bursts — e.g. replay-transcript backfill
# firing many observations in quick succession — don't overwrite each other.
TIMESTAMP=$(date -u +"%Y-%m-%d-%H-%M-%S")
OUTPUT_FILE="$OBS_DIR/$TIMESTAMP.md"

# Build the full prompt
FULL_PROMPT="Here is the conversation slice to observe. Write observations covering everything worth remembering.

---

$CONVERSATION

---

Output your observations using the XML format specified. Include <observations>, <current-task>, and <suggested-response>."

# Call Claude with the observation prompt
# Uses claude CLI in print mode with a fast model
# Signal to SessionStart hooks that this is a one-shot model call, not an
# interactive session: persona-inject.sh and obs-inject.sh both gate on this
# flag and emit nothing, so the call stays lean and cannot recurse.
export BRAIN_ONE_SHOT_SESSION=1
echo "🔬 Running observation pass..."
log info "claude-call-start" "{\"model\":\"claude-haiku-4-5-20251001\",\"promptChars\":${#FULL_PROMPT}}"
RESULT=$(echo "$FULL_PROMPT" | claude --print --strict-mcp-config --model claude-haiku-4-5-20251001 --system-prompt "$SYSTEM_PROMPT" 2>/dev/null)

if [ -z "$RESULT" ]; then
    log error "claude-call-failed" "{\"reason\":\"empty-result\"}"
    echo "Error: Claude returned empty result"
    exit 1
fi
log info "claude-call-ok" "{\"resultChars\":${#RESULT}}"

# Extract the observation content and convert XML to markdown
# Keep the XML structure but wrap in a markdown file with metadata header
cat > "$OUTPUT_FILE" << EOF
# Observation — $(date -u +"%Y-%m-%d %H:%M")

<!-- Generated by observe.sh -->

$RESULT
EOF

echo "✅ Observation written to: $OUTPUT_FILE"
log info "observation-written" "{\"path\":\"$OUTPUT_FILE\",\"chars\":$(wc -c < "$OUTPUT_FILE")}"

# Update observer-state.json
CURRENT_COUNT=$(jq -r '.unprocessedObservationCount // 0' "$STATE_FILE" 2>/dev/null || echo "0")
NEW_COUNT=$((CURRENT_COUNT + 1))

# Calculate character count of new observation
OBS_CHARS=$(wc -c < "$OUTPUT_FILE")
CURRENT_CHARS=$(jq -r '.unprocessedObservationChars // 0' "$STATE_FILE" 2>/dev/null || echo "0")
NEW_CHARS=$((CURRENT_CHARS + OBS_CHARS))

# Write updated state
jq --arg ts "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
   --arg file "memory/observations/$TIMESTAMP.md" \
   --argjson count "$NEW_COUNT" \
   --argjson chars "$NEW_CHARS" \
   '.lastObservationAt = $ts | .lastObservationFile = $file | .unprocessedObservationCount = $count | .unprocessedObservationChars = $chars' \
   "$STATE_FILE" > "$STATE_FILE.tmp" && mv "$STATE_FILE.tmp" "$STATE_FILE"

echo "📊 State updated: $NEW_COUNT unprocessed observations ($NEW_CHARS chars)"

# Rebuild current-context.md
bash "$SCRIPT_DIR/build-context.sh"

# Source ~/io-data/.env so both this script and any spawned child processes
# inherit EMBED_DRY_RUN, GEMINI_API_KEY, QDRANT_API_KEY etc.
# `set -a` auto-exports every assignment until `set +a`.
set -a
. ~/io-data/.env 2>/dev/null || true
set +a

# Locate a the-brain checkout that can run the CLI from source. BRAIN_ROOT
# names it explicitly; otherwise derive it from this script's own location,
# which holds when running straight from a checkout (the built layout has no
# cli/index.ts, so auto-index is skipped there).
resolve_brain_root() {
    local candidate
    for candidate in "${BRAIN_ROOT:-}" "$SCRIPT_DIR/../../../.."; do
        [ -n "$candidate" ] || continue
        if [ -f "$candidate/cli/index.ts" ]; then
            (cd "$candidate" && pwd)
            return 0
        fi
    done
    return 1
}

BRAIN_CHECKOUT="$(resolve_brain_root || true)"

# Auto-index new observation into Qdrant
if [ "${EMBED_DRY_RUN:-}" = "true" ]; then
  echo "[observe.sh] EMBED_DRY_RUN=true — skipping auto-index of $OUTPUT_FILE" >&2
else
  echo "[observe.sh] auto-indexing $OUTPUT_FILE" >&2
  if [ -n "$BRAIN_CHECKOUT" ]; then
    (cd "$BRAIN_CHECKOUT" && npx tsx cli/index.ts index --file "$OUTPUT_FILE" 2>/dev/null) &
  fi
fi

# Cross-link observation to brain files
if [ "${EMBED_DRY_RUN:-}" = "true" ]; then
  echo "[observe.sh] EMBED_DRY_RUN=true — skipping cross-link of $OUTPUT_FILE" >&2
else
  echo "[observe.sh] cross-linking $OUTPUT_FILE" >&2
  if [ -n "$BRAIN_CHECKOUT" ]; then
    (cd "$BRAIN_CHECKOUT" && npx tsx cli/index.ts cross-link "$OUTPUT_FILE" 2>/dev/null) &
  fi
fi

# Check if reflection is due (either count OR character threshold)
COUNT_THRESHOLD=$(jq -r '.reflectionTriggerThreshold // 5' "$STATE_FILE" 2>/dev/null || echo "5")
CHAR_THRESHOLD=$(jq -r '.reflectionCharThreshold // 8000' "$STATE_FILE" 2>/dev/null || echo "8000")
if [ "$NEW_COUNT" -ge "$COUNT_THRESHOLD" ] || [ "$NEW_CHARS" -ge "$CHAR_THRESHOLD" ]; then
    echo ""
    echo "⚡ Reflection threshold reached (count: $NEW_COUNT/$COUNT_THRESHOLD, chars: $NEW_CHARS/$CHAR_THRESHOLD)"
    log info "threshold-cross" "{\"newCount\":$NEW_COUNT,\"countThreshold\":$COUNT_THRESHOLD,\"newChars\":$NEW_CHARS,\"charThreshold\":$CHAR_THRESHOLD,\"autoReflect\":\"${AUTO_REFLECT:-0}\"}"
    if [ "${AUTO_REFLECT:-0}" = "1" ]; then
        echo "   AUTO_REFLECT=1 → chaining reflect.sh"
        log info "exit" "{\"status\":\"chaining-reflect\"}"
        export BRAIN_COMPONENT="reflect.sh"
        exec bash "$SCRIPT_DIR/reflect.sh"
    else
        echo "   Run: memory/tools/reflect.sh"
    fi
fi
log info "exit" "{\"status\":\"ok\",\"newCount\":$NEW_COUNT}"
