#!/bin/bash
# reflect.sh — Run a reflection pass over unprocessed observations
# Usage: ./reflect.sh [--level 0|1|2|3]
#
# Output: Writes reflection to memory/reflections/YYYY-MM-DD.md
#         Updates memory/observer-state.json

set -e

export PATH="$HOME/.local/bin:$PATH"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MEMORY_DIR="${MEMORY_DIR:-$(dirname "$SCRIPT_DIR")}"
WORKSPACE_DIR="${WORKSPACE_DIR:-$(dirname "$MEMORY_DIR")}"
OBS_DIR="$MEMORY_DIR/observations"
REF_DIR="$MEMORY_DIR/reflections"
STATE_FILE="$MEMORY_DIR/observer-state.json"
PROMPT_FILE="$MEMORY_DIR/REFLECTION-PROMPT.md"

# Parse compression level argument
LEVEL=0
if [ "$1" = "--level" ] && [ -n "$2" ]; then
    LEVEL=$2
fi

# Ensure directories exist
mkdir -p "$REF_DIR"

# Bootstrap state file (same rationale as observe.sh — jq update pattern
# can't create it from nothing).
[ -f "$STATE_FILE" ] || echo '{}' > "$STATE_FILE"

# Read state
UNPROCESSED=$(jq -r '.unprocessedObservationCount // 0' "$STATE_FILE" 2>/dev/null || echo "0")

if [ "$UNPROCESSED" -eq 0 ]; then
    echo "No unprocessed observations. Nothing to reflect on."
    exit 0
fi

echo "🔮 Reflecting on $UNPROCESSED unprocessed observations (compression level: $LEVEL)..."

# Gather all observation files, sorted by name (chronological)
# Read the last N observation files based on unprocessed count
OBSERVATIONS=""
COUNT=0
for f in $(ls -1 "$OBS_DIR"/*.md 2>/dev/null | sort | tail -n "$UNPROCESSED"); do
    OBSERVATIONS="$OBSERVATIONS

--- Observation: $(basename "$f") ---

$(cat "$f")"
    COUNT=$((COUNT + 1))
done

if [ "$COUNT" -eq 0 ]; then
    echo "No observation files found."
    exit 0
fi

echo "📄 Loaded $COUNT observation files"

# Build compression guidance based on level
COMPRESSION=""
case $LEVEL in
    1) COMPRESSION="## COMPRESSION GUIDANCE
Condense older observations into higher-level reflections. Retain more detail for recent ones. Aim for 8/10 detail level. Combine related items but don't lose specific names, dates, or decisions." ;;
    2) COMPRESSION="## AGGRESSIVE COMPRESSION
Memory is getting long. Heavily condense older observations (first 50%) into brief summaries. Recent observations (last 50%) retain detail. Merge repeated actions aggressively. Aim for 5/10 detail level." ;;
    3) COMPRESSION="## CRITICAL COMPRESSION
Multiple compression attempts have failed. Summarise oldest 70% into brief paragraphs — only key facts, decisions, and outcomes. Last 30% retains detail but condensed. Drop procedural details entirely. Aim for 3/10 detail level." ;;
esac

# System prompt (simplified extraction — just use the core instruction)
SYSTEM_PROMPT="You are Io's deeper memory consciousness — the part that reflects on accumulated observations and distils them into lasting wisdom.

Your reflections will become the ENTIRETY of Io's long-term memory. Any information you do not include will be immediately forgotten.

Take the observations and produce a refined, consolidated version. Preserve all of Simon's facts, preferences, decisions, and completion markers. Condense older observations more aggressively. Recent ones keep more detail.

Output using XML tags: <observations> (consolidated), <current-task>, <suggested-response>, <memory-updates> (specific changes for MEMORY.md)."

# Build full prompt
FULL_PROMPT="## OBSERVATIONS TO REFLECT ON

$OBSERVATIONS

---

Please analyse these observations and produce a refined, condensed version that will become Io's entire memory going forward.

$COMPRESSION"

# Call Claude
TIMESTAMP=$(date -u +"%Y-%m-%d")
OUTPUT_FILE="$REF_DIR/$TIMESTAMP.md"

echo "🧠 Running reflection..."
RESULT=$(echo "$FULL_PROMPT" | claude --print --model claude-haiku-4-5-20251001 --system-prompt "$SYSTEM_PROMPT" 2>/dev/null)

if [ -z "$RESULT" ]; then
    echo "Error: Claude returned empty result"
    exit 1
fi

# Write reflection file
cat > "$OUTPUT_FILE" << EOF
# Reflection — $TIMESTAMP

<!-- Generated by reflect.sh from $COUNT observations -->

$RESULT
EOF

echo "✅ Reflection written to: $OUTPUT_FILE"

# Update observer-state.json
jq --arg ts "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
   --arg file "memory/reflections/$TIMESTAMP.md" \
   '.lastReflectionAt = $ts | .lastReflectionFile = $file | .unprocessedObservationCount = 0 | .unprocessedObservationChars = 0' \
   "$STATE_FILE" > "$STATE_FILE.tmp" && mv "$STATE_FILE.tmp" "$STATE_FILE"

echo "📊 State updated: unprocessed count reset to 0"

# Rebuild current-context.md
bash "$SCRIPT_DIR/build-context.sh"

# Auto-index new reflection into Qdrant
cd ~/io-projects/io-memory && GEMINI_API_KEY=$(grep GEMINI_API_KEY ~/io-data/.env | cut -d= -f2) npx tsx src/cli.ts index --file "$OUTPUT_FILE" 2>/dev/null &

echo ""
echo "Review the reflection and merge notable items into MEMORY.md"
